/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.mk.tc.starter;

import java.util.Properties;
import java.util.TimeZone;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import pl.mk.tc.FileSynchronizer;
import pl.mk.util.PropertiesReader;

public class Starter {

	/**
	 * Application name.
	 */
	public static final String APPLICATION_NAME = "File Synchronizer";

	private static final String PROPERTIES_FILEPATH = "./main.properties";

	private static Logger log = LogManager.getLogger(Starter.class);

	public static void main(String[] args) {
		Starter.log.info("START");
		Starter.log.info(Starter.APPLICATION_NAME);
		Starter.log.info("-----------------------------");

		try {
			final PropertiesReader propertiesReader = new PropertiesReader();
			final Properties properties = propertiesReader.initialize(Starter.PROPERTIES_FILEPATH);
			FileSynchronizer fs = new FileSynchronizer(properties);
			TimeZone.setDefault(TimeZone.getTimeZone("Poland"));

			internalMain(fs);

			Starter.log.info("-----------------------------");
			Starter.log.info("APPLICATION FINISHED OK");
		} catch (final Exception e) {
			Starter.log.error("-----------------------------");
			Starter.log.error("APPLICATION FINISHED WITH ERROR:", e);
		}
	}

	private static void internalMain(FileSynchronizer fs) {
		fs.run();
	}
}
